# Generated by Django 6.0.6 on 2026-06-13 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('material_type', models.CharField(choices=[('document', 'Documento'), ('presentation', 'Presentación'), ('video', 'Video (enlace)'), ('link', 'Enlace web'), ('exercise', 'Ejercicio'), ('guide', 'Guía'), ('other', 'Otro')], default='document', max_length=20, verbose_name='Tipo')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/', verbose_name='Archivo')),
                ('url', models.URLField(blank=True, verbose_name='Enlace externo')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible para alumnos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='Curso')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-created_at'],
            },
        ),
    ]
