# Generated by Django 6.0.6 on 2026-06-13 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre corto')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('section', models.CharField(blank=True, max_length=20, verbose_name='Sección')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre'), (3, 'Anual'), (4, 'Verano')], verbose_name='Período')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('color', models.CharField(default='#4361ee', help_text='Color hexadecimal para identificar el curso', max_length=7, verbose_name='Color del curso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.university', verbose_name='Universidad')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-year', '-semester', 'name'],
                'unique_together': {('professor', 'code', 'section', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('exam', 'Examen / Prueba'), ('quiz', 'Control'), ('task', 'Tarea'), ('project', 'Proyecto'), ('other', 'Otro')], default='exam', max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Sala / Lugar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_dates', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Fecha de evaluación',
                'verbose_name_plural': 'Fechas de evaluación',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Curso')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
