# Generated by Django 6.0.6 on 2026-06-13 23:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('grade_type', models.CharField(choices=[('exam', 'Prueba / Examen'), ('quiz', 'Control'), ('task', 'Tarea'), ('project', 'Proyecto'), ('participation', 'Participación'), ('other', 'Otro')], default='exam', max_length=20, verbose_name='Tipo')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Porcentaje de esta nota en la nota final (ej: 30 = 30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ponderación (%)')),
                ('max_score', models.DecimalField(decimal_places=1, default=Decimal('7.0'), max_digits=5, verbose_name='Nota máxima')),
                ('min_passing', models.DecimalField(decimal_places=1, default=Decimal('4.0'), max_digits=4, verbose_name='Nota mínima de aprobación')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de evaluación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Comentario')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_published', models.BooleanField(default=False, help_text='Si está marcada, los alumnos pueden ver esta nota', verbose_name='Publicada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_columns', to='courses.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Columna de nota',
                'verbose_name_plural': 'Columnas de notas',
                'ordering': ['order', 'created_at'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))], verbose_name='Nota')),
                ('is_absent', models.BooleanField(default=False, verbose_name='Ausente')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario del profesor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.gradecolumn', verbose_name='Columna')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('student', 'column')},
            },
        ),
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighted_average', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Promedio ponderado')),
                ('is_passing', models.BooleanField(blank=True, null=True, verbose_name='Aprobado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_reports', to='courses.course', verbose_name='Curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_reports', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Reporte de notas',
                'verbose_name_plural': 'Reportes de notas',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
